apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-headless
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: 8080
      targetPort: mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
    - name: submission
      port: {{ .Values.service.ports.submission }}
      targetPort: submission
    - name: imaps
      port: {{ .Values.service.ports.imaps }}
      targetPort: imaps

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-web
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: http-web
      port: 8080
      targetPort: mgmt