apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    longhorn.io/number-of-replicas: "2"
  name: home-assistant-config-lh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
