apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-os-ca
  namespace: default
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIJN4aRMNUl+GoyMA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
    BAMTC3VuaWZpLmxvY2FsMB4XDTI2MDkxNTA1MDAzOFoXDTI4MTIxODA1MDAzOFow
    FjEUMBIGA1UEAxMLdW5pZmkubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDCB4gIkUq5rE57zWNseFRIP4zszmQPuJe5pfG/F8gwWN0p+lRBD6+6
    jIIfLeRASqVU3QrgCcUh0b+NFJ5LD99bvW0+D0LlPZ+W73J2WPqypL+LxAWWI0X5
    EP3WECRJs2s4MV7Xu0uXxgTJP817dUc58BvOZoK4F57ijpFM7Zto9nX/aykuHKSF
    UfORRZxLTyY9w1X6xH1SaJAAjw4Nyxef6mrK5EdBEuc9KpXcJJkquhGkW8fNTwlX
    N7wvMJYisuGtl/IGdVSMhF+66pG6GZuuh1W1wRExJugwcszAyzEm57fapUruz6KX
    MU5uLDKz7uhZQKbvFjo/RrgKhkHy4sWbAgMBAAGjgYUwgYIwCwYDVR0PBAQDAgL0
    MDEGA1UdJQQqMCgGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUF
    BwMIMEAGA1UdEQQ5MDeCC3VuaWZpLmxvY2Fsgglsb2NhbGhvc3SCBVs6OjFdhwR/
    AAABhxD+gAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IBAQCPtRmfCzUz
    UK/pzvMTY0nShK3rXm3ufmt6YAguJIxvjtEF4HwzYF8yS1hfV5FXXtkm5tLmza+Y
    6GtQROmmnT8Bb0zHaJhn/b0BRvMIJJu5DCYGwOf1StiaHA1kUuR1kTieIsSib8EH
    Wk4VPUQ81XC67q/zfzIeuMqExDv5GJyAUACIFcp22ofTaguoM6zyC6rFFkYSfxzL
    UyEkthGnjbM+lvyrCMFy9vTgaMt/IRz4mAPzJjkIAs2gsBGd6o2VnXK514Z2KNhj
    SZijWTp52NxowUlQel7529HHG6569OBozaVGxsCgN93Oo/zGTmV9o8/JQxmxcYLi
    N957JAtItPRO
    -----END CERTIFICATE-----
