apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    longhorn.io/number-of-replicas: "3"
  name: litellm-redis-data-lh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
