apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-filer-config
data:
  filer.toml: |
    [leveldb2]
    enabled = true
    dir = "./filerldb2"

    [filer.options]
    max_file_name_length = 0
