apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-master-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: {requests: {storage: 1Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-filer-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-cnpg
  resources: {requests: {storage: 10Gi}}
