apiVersion: v1
kind: Service
metadata:
  name: webserver-dev-externalip
  labels:
    app: webserver-dev-externalip
spec:
  type: ClusterIP
  selector:
    app: webserver-dev
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http-authserver
---
apiVersion: v1
kind: Endpoints
metadata:
  name: webserver-dev-externalip
subsets:
- addresses:
  - ip: 192.168.1.32
  ports:
  - name: webserver-dev
    port: 8080
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: authserver-dev-externalip
  labels:
    app: authserver-dev-externalip
spec:
  type: ClusterIP
  selector:
    app: authserver-dev
  clusterIP: None
  ports:
    - port: 80
      targetPort: 12143
      protocol: TCP
      name: http-authserver
---
apiVersion: v1
kind: Endpoints
metadata:
  name: authserver-dev-externalip
subsets:
- addresses:
  - ip: 192.168.1.32
  ports:
  - name: authserver-dev
    port: 12143
    protocol: TCP

