# A deployment for an Enigmatic Skies NeoForge modpack server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: nas
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      volumes:
        - name: data
          hostPath:
            path: /tank/minecraft/skies
            type: Directory
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2025.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: NEOFORGE
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/enigmatic-skies"
            - name: VERSION
              value: "1.21.1"
            - name: MEMORY
              value: "8G"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "true"
          ports:
            - containerPort: 25565
              protocol: TCP
              name: game
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 2
              memory: 6Gi
            limits:
              memory: 8Gi
          startupProbe:
            tcpSocket:
              port: game
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-game
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 32565
      protocol: TCP
  selector:
    app: minecraft