apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: matrix
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.5.10"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: coturn
  ports:
    - name: stun-turn
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: stun-turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
