apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-genai-tls-ca
  namespace: default
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdTCCARygAwIBAgIQblStEpZVJQD7WicYtbHq/DAKBggqhkjOPQQDAjAbMRkw
    FwYDVQQDExB0ZW1wb3JhbC1ncnBjLWNhMB4XDTI2MDcxNTE0Mjk0MVoXDTI2MTAx
    MzE0Mjk0MVowGzEZMBcGA1UEAxMQdGVtcG9yYWwtZ3JwYy1jYTBZMBMGByqGSM49
    AgEGCCqGSM49AwEHA0IABM6AXlwNQDsq4z/98cQaTDwTxCVB7/OQ+4Sw0fpN9RS+
    d9+ZHj7HvwzSz0jSETDHL5/F3o+K/JZzw/AMhD1FQ96jQjBAMA4GA1UdDwEB/wQE
    AwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTo7NYkmcisf4pc/xYIeuhI
    pyqhBTAKBggqhkjOPQQDAgNHADBEAiB58ZYJN5/exq7hX6/b8Em/bxZEVxzqbVuf
    M5iyIUVqFwIgGzBShCip8I5xIwOIltA3tOoO9HCwcTW+a5cLVSgWn80=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDyzCCArOgAwIBAgIQA8Kq2tAQdxyBeMGqFaJo7TANBgkqhkiG9w0BAQsFADBs
    MQswCQYDVQQGEwJVUzERMA8GA1UEChMIam9objIxNDMxGjAYBgNVBAMTEWt1YmUu
    am9objIxNDMuY29tMS4wLAYDVQQFEyU0OTk4NDU0OTIzNjc1MzQwNDE1NjQ3MzI3
    MzcxNTU2NzEwNjM3MB4XDTI2MDcxODE3MjUyNFoXDTI2MDcxOTE3MjUzNFowbDEL
    MAkGA1UEBhMCVVMxETAPBgNVBAoTCGpvaG4yMTQzMRowGAYDVQQDExFrdWJlLmpv
    aG4yMTQzLmNvbTEuMCwGA1UEBRMlNDk5ODQ1NDkyMzY3NTM0MDQxNTY0NzMyNzM3
    MTU1NjcxMDYzNzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL69Smrc
    RSxg6gtWoFWP3dhVKUy4KgR8+BZUT6Bwf3jCCh1J5vUBKNHQeY40phdHhsWqkAtP
    tqeVc6mbSMFLN89b7hCsCzLBpQQpjw008Xg1nzM/YYLdp7qVpSZqYn3fQDlwAtPr
    E64AItdnLOQDoVaEmYfBG0nvSd7b9kq7ZchWccAoXdzIUvnKLv7CzJdWH7A9oADy
    2l0+rXLoUtJ2454b1H3fbsFPR9xeKe7QYPsGJNsCYZagKA5/ig1gCzWilPtFV8sL
    adINtOU3pb6+3b0EMLAj1rEmfIcN453QLprgwXh7Ja3X+cDyjEnYF7Ut4eV6tboE
    /1rYDxFGvALt+3UCAwEAAaNpMGcwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFHK3RYPa3DV3wlqjJwIlk3QFBujhMCUGA1UdEQQeMByG
    GnNwaWZmZTovL2t1YmUuam9objIxNDMuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQCo
    qCBmZw159EpAppnxgBngAovdj0m2KHIolfkHtxe7q3irDMbLqMw2rVBwOC6I8QeQ
    q7+QnHAJxL7xlRSuukVt11DU2/JbrjRWPl38GgMwIFGLcXPwHlMowEeTNBomajYo
    o/mnN5WZKmWzTeIiHQPwFdtSQIwLu3cdOeN5gvQW+wRJMhFhVO5E1b+aXoF00a6A
    vcQ2lqPPldt0Kb253vAROmPk/hnsbQAcLadpK6Jv6tm1hYgRVfxincEqKeCJ+a5p
    8eWW6LE2RrNPGmFxG5nNBpMmfeMfpgKURjIYA0jI78ksiykMonW3jYHxJc9JB4uD
    IZ5l2LcUpVP6KwNfShkl
    -----END CERTIFICATE-----
