apiVersion: temporal.io/v1alpha1
kind: Connection
metadata:
  name: frigate-genai-temporal
spec:
  hostPort: temporal-frontend.default.svc.cluster.local:7233
  tls:
    serverName: temporal-frontend.default.svc.cluster.local
