apiVersion: temporal.io/v1alpha1
kind: WorkerResourceTemplate
metadata:
  name: frigate-genai-ffmpeg-keda
spec:
  workerDeploymentRef: {name: frigate-genai-ffmpeg}
  template:
    apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    spec:
      scaleTargetRef: {}
      minReplicaCount: 0
      maxReplicaCount: 5
      pollingInterval: 15
      cooldownPeriod: 120
      triggers:
      - type: temporal
        metadata:
          endpoint: temporal-frontend.default.svc.cluster.local:7233
          namespace: default
          taskQueue: ffmpeg
          targetQueueSize: "5"
          activationTargetQueueSize: "2"
          queueTypes: activity
          workerDeploymentName: frigate-genai-ffmpeg
          workerDeploymentBuildId: ""
