apiVersion: temporal.io/v1alpha1
kind: WorkerResourceTemplate
metadata:
  name: frigate-genai-ffmpeg-keda
spec:
  workerDeploymentRef: {name: frigate-genai-ffmpeg}
  template:
    apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    spec:
      scaleTargetRef: {}
      minReplicaCount: 0
      maxReplicaCount: 3
      cooldownPeriod: 600
      triggers:
      - type: temporal
        metadata:
          endpoint: temporal-frontend.default.svc.cluster.local:7233
          taskQueue: "genai-tasks-ffmpeg"
          queueTypes: activity
          targetQueueSize: "2"
