apiVersion: temporal.io/v1alpha1
kind: WorkerResourceTemplate
metadata:
  name: frigate-genai-gemini-keda
spec:
  workerDeploymentRef: {name: frigate-genai-gemini}
  template:
    apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    spec:
      scaleTargetRef: {}
      minReplicaCount: 1
      maxReplicaCount: 10
      pollingInterval: 15
      cooldownPeriod: 120
      triggers:
      - type: temporal
        metadata:
          endpoint: temporal-frontend.default.svc.cluster.local:7233
          namespace: default
          taskQueue: genai-gemini
          targetQueueSize: "20"
          activationTargetQueueSize: "5"
          queueTypes: activity
          workerDeploymentName: frigate-genai-gemini
          workerDeploymentBuildId: v103
