apiVersion: temporal.io/v1alpha1
kind: WorkerResourceTemplate
metadata:
  name: frigate-genai-ollama-keda
spec:
  workerDeploymentRef: {name: frigate-genai-ollama}
  template:
    apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    spec:
      scaleTargetRef: {}
      minReplicaCount: 0
      maxReplicaCount: 5
      pollingInterval: 15
      cooldownPeriod: 120
      triggers:
      - type: temporal
        metadata:
          endpoint: temporal-frontend.default.svc.cluster.local:7233
          namespace: ""
          workerDeploymentName: ""
          workerDeploymentBuildId: ""
          taskQueue: genai-tasks-ollama
          targetQueueSize: "3"
          activationTargetQueueSize: "1"
          queueTypes: activity
