apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frigate-genai-ollama
spec:
  scaleTargetRef: {name: frigate-genai-ollama}
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
  - type: temporal
    metadata:
      endpoint: temporal-frontend.default.svc.cluster.local:7233
      namespace: default
      taskQueue: "genai-tasks-ollama"
      queueTypes: activity
      targetQueueSize: "1"
