apiVersion: v1
kind: Service
metadata:
  name: frigate-genai-triggers
  labels: {app: frigate-genai-triggers}
spec:
  type: ClusterIP
  selector: {app: frigate-genai-triggers}
  ports:
    - port: 9090
      targetPort: 8080
      protocol: TCP
      name: http
