# Source: livekit-server/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-server
data:
  config.yaml: |
    key_file: keys.yaml
    keys: {}
    log_level: info
    port: 7880
    redis: {}
    rtc:
      tcp_port: 7881
      udp_port: 50000
      use_external_ip: false
      node_ip: 192.168.6.22
    turn:
      enabled: true
      domain: turn.john2143.com
      tls_port: 5349
      external_tls: false
      cert_file: /etc/livekit/turn/tls.crt
      key_file: /etc/livekit/turn/tls.key
      relay_range_start: 50001
      relay_range_end: 50064

