apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: services
  namespace: metallb-system
spec:
  addresses:
  - 192.168.6.10-192.168.6.50
  - fd00:6::10-fd00:6::50
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: control-plane-vip
  namespace: metallb-system
spec:
  addresses:
  - 192.168.5.10-192.168.5.10
  autoAssign: false
