apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: default
  annotations:
    metallb.io/address-pool: control-plane-vip
    metallb.io/loadBalancerIPs: "192.168.5.10"
spec:
  type: LoadBalancer
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubernetes-api
  namespace: default
  labels:
    kubernetes.io/service-name: kubernetes-api
    endpointslice.kubernetes.io/managed-by: custom
addressType: IPv4
endpoints:
  - addresses: ["192.168.5.36"]
    conditions:
      ready: true
  - addresses: ["192.168.5.76"]
    conditions:
      ready: true
  - addresses: ["192.168.5.175"]
    conditions:
      ready: true
ports:
  - port: 6443
    protocol: TCP
