apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-recordings
spec:
  capacity:
    storage: 18Ti
  accessModes: [ReadWriteMany]
  nfs:
    server: 192.168.5.175
    path: /tank/frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-recordings
  namespace: default
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  resources:
    requests:
      storage: 18Ti
