apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: default
spec:
  selector: {app: frigate}
  ports:
    - {name: http, port: 5000, targetPort: 5000, nodePort: 30500}
    - {name: go2rtc-api, port: 1984, targetPort: 1984}
  type: NodePort
