apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    longhorn.io/number-of-replicas: "2"
  name: mosquitto-data-lh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2
  volumeName: pvc-e8a098fa-835e-4e9a-9394-37f363475db2
