apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
    storageClass: longhorn-cnpg
  walStorage:
    size: 2Gi
    storageClass: longhorn-cnpg
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        createDB: true
        passwordSecret:
          name: keycloak-db-password
          key: password
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
