apiVersion: v1
kind: Service
metadata:
  name: unifi-next-mongodb
  labels:
    app: unifi-next-mongodb
spec:
  type: ClusterIP
  selector:
    app: unifi-next-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
