apiVersion: v1
kind: Service
metadata:
  name: unifi-inform
  labels:
    app: unifi
spec:
  type: LoadBalancer
  selector:
    app: unifi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: inform
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-web
  labels:
    app: unifi
spec:
  type: NodePort
  selector:
    app: unifi
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
      name: web-ui
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-discovery
  labels:
    app: unifi
spec:
  type: LoadBalancer
  selector:
    app: unifi
  ports:
    - port: 10001
      targetPort: 10001
      protocol: UDP
      name: discovery
