apiVersion: v1
kind: Service
metadata:
  name: unifi
  labels:
    app: unifi
spec:
  type: ClusterIP
  selector:
    app: unifi
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: web-ui
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: inform
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: stun
    - port: 10001
      targetPort: 10001
      protocol: UDP
      name: discovery
    - port: 6789
      targetPort: 6789
      protocol: TCP
      name: speed-test
---
# Device inform - must be reachable directly by UniFi devices on the network
apiVersion: v1
kind: Service
metadata:
  name: unifi-inform
spec:
  type: LoadBalancer
  selector:
    app: unifi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: inform
---
# Web UI
apiVersion: v1
kind: Service
metadata:
  name: unifi-web
spec:
  type: NodePort
  selector:
    app: unifi
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
      name: web-ui
---
# Device discovery
apiVersion: v1
kind: Service
metadata:
  name: unifi-discovery
spec:
  type: LoadBalancer
  selector:
    app: unifi
  ports:
    - port: 10001
      targetPort: 10001
      protocol: UDP
      name: discovery
