apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  labels:
    app: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-secret-state
  labels:
    app: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-state
  labels:
    app: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-secret-state
