apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: default
  labels:
    app: rustfs
  annotations:
    longhorn.io/numberOfReplicas: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 600Gi
