apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data-pocket-id-0
  namespace: pocket-id
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-3
  volumeName: pocket-id-restored-pv
