apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asciinema-data
  namespace: default
  labels:
    recurring-job.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-3
  resources:
    requests:
      storage: 10Gi
