apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: traefik
  listeners:
    - name: acme-http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: Same
    - name: rots-https
      protocol: HTTPS
      port: 8443
      hostname: rots.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: rots-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: prod-rots-https
      protocol: HTTPS
      port: 8443
      hostname: prod.rots.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: rots-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: auth-prod-rots-https
      protocol: HTTPS
      port: 8443
      hostname: auth.prod.rots.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: rots-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: dev-rots-https
      protocol: HTTPS
      port: 8443
      hostname: dev.rots.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: rots-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: auth-dev-rots-https
      protocol: HTTPS
      port: 8443
      hostname: auth.dev.rots.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: rots-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: auth-john2143-https
      protocol: HTTPS
      port: 8443
      hostname: auth.john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: auth-john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: authentik
    - name: auth-ts-2143-https
      protocol: HTTPS
      port: 8443
      hostname: auth.ts.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: auth-ts-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: authentik
    - name: john2143-https
      protocol: HTTPS
      port: 8443
      hostname: john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: home-ts-2143-https
      protocol: HTTPS
      port: 8443
      hostname: home.ts.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: home-ts-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: pihole-ts-2143-https
      protocol: HTTPS
      port: 8443
      hostname: pihole.ts.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: pihole-ts-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: fs-john2143-https
      protocol: HTTPS
      port: 8443
      hostname: fs.john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: fs-john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: fsui-john2143-https
      protocol: HTTPS
      port: 8443
      hostname: fsui.john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: fsui-john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: files-john2143-https
      protocol: HTTPS
      port: 8443
      hostname: files.john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: files-john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: files-ui-ts-2143-https
      protocol: HTTPS
      port: 8443
      hostname: files-ui.ts.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: files-ui-ts-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: net-john2143-https
      protocol: HTTPS
      port: 8443
      hostname: net.john2143.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: net-john2143-com-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: net-2143-https
      protocol: HTTPS
      port: 8443
      hostname: net.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: net-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: factorio-https
      protocol: HTTPS
      port: 8443
      hostname: factorio.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: factorio-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: images-2143-https
      protocol: HTTPS
      port: 8443
      hostname: images.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: images-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: longhorn-ts-2143-https
      protocol: HTTPS
      port: 8443
      hostname: longhorn.ts.2143.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: longhorn-ts-2143-me-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: longhorn-system
    # These are defined as nodeports instead
    #- name: factorio-udp
      #protocol: UDP
      #port: 34197
      #allowedRoutes:
        #namespaces:
          #from: Same
    #- name: teamspeak-udp
      #protocol: UDP
      #port: 9987
      #allowedRoutes:
        #namespaces:
          #from: Same
    #- name: teamspeak-tcp
      #protocol: TCP
      #port: 30033
      #allowedRoutes:
        #namespaces:
          #from: Same
