apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: default
spec:
  parentRefs:
    - name: shared-gateway
      sectionName: grafana-john2143-https
  hostnames: [grafana.john2143.com]
  rules:
    - backendRefs:
        - name: grafana
          namespace: observability
          port: 80
