apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: balabusta
  namespace: default
spec:
  target:
    service: balabusta
    port: 80
  rules:
    - hosts:
        - balabusta.homes
  scalingMetric:
    concurrency:
      targetValue: 10
