apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webserver
  namespace: default
spec:
  parentRefs:
    - name: shared-gateway
      sectionName: rots-https
    - name: shared-gateway
      sectionName: prod-rots-https
  hostnames:
    - rots.2143.me
    - prod.rots.2143.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webserver
          port: 80
