apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2026.2.2
    helm:
      releaseName: authentik
      values: |
        global:
          envFrom:
            - secretRef:
                name: authentik-secrets
        authentik: {}
        server:
          replicas: 1
          ingress:
            enabled: false
          volumes:
            - name: custom-blueprints
              configMap:
                name: custom-blueprints
          volumeMounts:
            - name: custom-blueprints
              mountPath: /blueprints/custom
              readOnly: true
        worker:
          replicas: 1
          volumes:
            - name: custom-blueprints
              configMap:
                name: custom-blueprints
          volumeMounts:
            - name: custom-blueprints
              mountPath: /blueprints/custom
              readOnly: true
        postgresql:
          enabled: false
        redis:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
