apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: friend-sites
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: aross
  template:
    metadata:
      name: "friend-{{.name}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/2143-Labs/argo.git
        targetRevision: HEAD
        path: "workloads/friends/{{.name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
