apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/2143-Labs/argo.git
    targetRevision: HEAD
    path: workloads/pocket-id
  destination:
    server: https://kubernetes.default.svc
    namespace: pocket-id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
