apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile-mariadb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.x
    helm:
      releaseName: seafile-mariadb
      values: |
        auth:
          rootPassword: "changeme-root"
          database: seafile_db
          username: seafile
          password: "changeme-seafile"
        
        primary:
          persistence:
            enabled: true
            storageClass: longhorn
            size: 10Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
