apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spire-routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/2143-Labs/argo.git
    targetRevision: HEAD
    path: workloads/spire-routes
  destination:
    server: https://kubernetes.default.svc
    namespace: spire-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
