apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.24.4
    helm:
      releaseName: tempo
      values: |
        replicas: 2
        tempo:
          storage:
            trace:
              backend: s3
              s3:
                endpoint: files.john2143.com
                bucket: tempo-blocks
                insecure: false
                forcepathstyle: true
                access_key: ${S3_ACCESS_KEY}
                secret_key: ${S3_SECRET_KEY}
          retention: 168h
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          extraArgs:
            config.expand-env: "true"
          extraEnvFrom:
            - secretRef:
                name: o11y-rustfs-buckets
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
