apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/2143-Labs/argo.git
    targetRevision: HEAD
    path: workloads/temporal-db
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/enablePDB
        - /spec/enableSuperuserAccess
        - /spec/failoverDelay
        - /spec/logLevel
        - /spec/maxSyncReplicas
        - /spec/minSyncReplicas
        - /spec/monitoring
        - /spec/affinity
        - /spec/primaryUpdateStrategy
        - /spec/primaryUpdateMethod
        - /spec/backup
