apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpn-endpoints
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: de-mullvad
            country: Germany
            city: dusseldorf
            hostname: de-mullvad
            pvcName: de-mullvad-state
            replicas: 1
            mullvadRotationNonce: 1
          - name: ee-mullvad
            country: Estonia
            city: tallinn
            hostname: ee-mullvad
            pvcName: ee-mullvad-state
            replicas: 1
            mullvadRotationNonce: 1
          - name: jp-mullvad
            country: Japan
            city: tokyo
            hostname: jp-mullvad
            pvcName: jp-mullvad-state
            replicas: 1
            mullvadRotationNonce: 1
          - name: za-mullvad
            country: South Africa
            city: johannesburg
            hostname: za-mullvad
            pvcName: za-mullvad-state
            replicas: 1
            mullvadRotationNonce: 1
  template:
    metadata:
      name: "vpn-endpoint-{{.name}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
        - pre-delete-finalizer.argocd.argoproj.io
        - pre-delete-finalizer.argocd.argoproj.io/cleanup
    spec:
      project: default
      source:
        repoURL: https://github.com/2143-Labs/argo.git
        targetRevision: HEAD
        path: workloads/vpn-endpoints
        helm:
          releaseName: "{{.name}}"
          parameters:
            - { name: name, value: "{{.name}}" }
            - { name: country, value: "{{.country}}" }
            - { name: city, value: "{{.city}}" }
            - { name: hostname, value: "{{.hostname}}" }
            - { name: pvcName, value: "{{.pvcName}}" }
            - { name: replicas, value: "{{.replicas}}" }
            - { name: mullvadRotationNonce, value: "{{.mullvadRotationNonce}}" }
      destination:
        server: https://kubernetes.default.svc
        namespace: vpn-endpoints
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
