apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 5Gi
    storageClass: longhorn-cnpg
  walStorage:
    size: 4Gi
    storageClass: longhorn-cnpg
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      postInitSQL:
        - CREATE DATABASE temporal_visibility OWNER temporal
  managed:
    roles:
      - name: temporal
        ensure: present
        login: true
        passwordSecret:
          name: temporal-db-password
  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 scram-sha-256
