# A deployment for a factorio server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      volumes:
      - name: factorio-saves
        persistentVolumeClaim:
          claimName: factorio-saves-pvc
      - name: factorio-configs
        persistentVolumeClaim:
          claimName: factorio-configs-pvc
      - name: factorio-db
        persistentVolumeClaim:
          claimName: factorio-db-pvc
      - name: factorio-mod-packs
        persistentVolumeClaim:
          claimName: factorio-mod-packs-pvc

      containers:
      - name: factorio
        image: ofsm/ofsm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: &http_port 80
        - containerPort: &game_port 34197
        env:
        - name: FSM_AUTOSTART
          value: "true"
        - name: FSM_MODPACK_DIR
          value: /mnt/modpacks/
        #- name: FSM_FACTORIO_SAVES_DIR
          #value: /mnt/saves
        #- name: FSM_FACTORIO_MODS_DIR
          #value: /mnt/config/mods/
        #- name: FSM_FACTORIO_CONFIG_DIR
          #value: ../../mnt/config/
        - name: SQ_LITE_DATABASE_FILE
          value: /mnt/db/sqlite.db

        volumeMounts:
        - mountPath: /opt/factorio/saves/
          name: factorio-saves
        - mountPath: /opt/factorio/config/
          name: factorio-configs
        - mountPath: /mnt/db
          name: factorio-db
        - mountPath: /mnt/mod_packs/
          name: factorio-mod-packs
        resources:
          requests:
            memory: "3000Mi"
            cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: factorio-http
spec:
  ports:
  #type: NodePort
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 31180
    protocol: TCP
    name: http

  selector:
    app: factorio
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-game
spec:
  type: NodePort
  ports:
  - port: 34197
    targetPort: 34197
    nodePort: 31111
    protocol: UDP

  selector:
    app: factorio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-saves-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-configs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-mod-packs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: local-path
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factorio-web-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - factorio.2143.me
      secretName: factorio-2143-me-tls
  rules:
    - host: factorio.2143.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: factorio-http
                port:
                  number: 80
