apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: steam-lobby-db
  namespace: steam-lobby
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  storage:
    size: 10Gi
    storageClass: longhorn-cnpg
  walStorage:
    size: 4Gi
    storageClass: longhorn-cnpg
  bootstrap:
    initdb:
      database: lobby
      owner: lobby
      secret:
        name: steam-lobby-db-password
  managed:
    roles:
      - name: lobby
        ensure: present
        login: true
        passwordSecret:
          name: steam-lobby-db-password
