---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik
  namespace: default
spec:
  gatewayClassName: traefik

  # Only Routes from the same namespace are allowed.
  listeners:
    - name: udp
      protocol: UDP
      port: 9987
      allowedRoutes:
        namespaces:
          from: Same
    - name: fileserver
      protocol: TCP
      port: 30033
      allowedRoutes:
        namespaces:
          from: Same
