apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    longhorn.io/number-of-replicas: "2"
  name: teamspeak-all-lh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: longhorn-2
  volumeName: pvc-f06012f1-ffff-4279-9905-144359eb15cc
