apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: element-web
  namespace: matrix
spec:
  scaleTargetRef:
    name: element-web
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 900
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: element-web
