apiVersion: apps/v1
kind: Deployment
metadata:
  name: john2143-worker
  labels:
    app: john2143-worker
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: john2143-worker
  template:
    metadata:
      labels:
        app: john2143-worker
    spec:
      volumes:
        - name: workdir
          emptyDir:
            sizeLimit: 10Gi
        - name: spiffe-workload-api
          csi:
            driver: csi.spiffe.io
            readOnly: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                      - general
      containers:
        - name: worker
          image: ghcr.io/john2143/john2143.com-worker:190
          imagePullPolicy: IfNotPresent
          env:
            - name: RUN_MODE
              value: "worker"
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: worker-uri
            - name: MINIO_ENDPOINT_URL
              value: "https://files.john2143.com"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
            - name: TEMPORAL_TLS
              value: "true"
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spiffe-workload-api/spire-agent.sock"
            - name: S3_ENDPOINT_URL
              value: "https://imagehost-files.nyc3.digitaloceanspaces.com"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: S3_SECRET_KEY
            - name: BUCKET
              value: "imagehost-files"
            - name: FOLDER
              value: "public-prod"
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: workdir
              mountPath: /tmp/juush-worker
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
