apiVersion: temporal.io/v1alpha1
kind: WorkerDeployment
metadata:
  name: john2143-com-worker
  labels: {app: john2143-com-worker}
spec:
  workerOptions:
    connectionRef: {name: john2143-temporal}
    temporalNamespace: john2143-com
    unsafeCustomBuildID: "209"
  rollout:
    strategy: AllAtOnce
  sunset:
    scaledownDelay: 10m
    deleteDelay: 1h
  template:
    metadata:
      labels: {app: john2143-com-worker, app.kubernetes.io/part-of: john2143-com}
      annotations:
        linkerd.io/inject: disabled
        config.linkerd.io/skip-outbound-ports: "7233"
    spec:
      serviceAccountName: john2143-worker
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                      - general
      containers:
        - name: worker
          image: ghcr.io/john2143/john2143.com-worker:209
          imagePullPolicy: IfNotPresent
          env:
            - name: RUN_MODE
              value: "worker"
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: worker-uri
            - name: MINIO_ENDPOINT_URL
              value: "https://files.john2143.com"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: S3_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: S3_SECRET_KEY
            - {name: TEMPORAL_ADDRESS, value: "temporal-frontend.default.svc.cluster.local:7233"}
            - {name: TEMPORAL_WORKER_BUILD_ID, value: "209"}
            - {name: TEMPORAL_DEPLOYMENT_NAME, value: "john2143-com-worker"}
            - name: S3_ENDPOINT_URL
              value: "https://nyc3.digitaloceanspaces.com"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: S3_SECRET_KEY
            - name: BUCKET
              value: "imagehost-files"
            - name: FOLDER
              value: "public-prod"
            - name: NODE_ENV
              value: "production"
          resources:
            requests: {memory: "256Mi", cpu: "100m"}
            limits: {memory: "2Gi", cpu: "2000m"}
